-- AlterTable
ALTER TABLE "VoucherRequest" ADD COLUMN     "code" TEXT NOT NULL DEFAULT 'REQUESTED',
ADD COLUMN     "discountType" TEXT NOT NULL DEFAULT 'PERCENTAGE',
ADD COLUMN     "discountValue" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "minPurchase" DOUBLE PRECISION,
ADD COLUMN     "validUntil" TIMESTAMP(3);
